spring:
  datasource:
    master:
      url: jdbc:mysql://localhost:33061/mydb?useSSL=false
      username: root
      password: root
      jpa:
        hibernate:
          ddl-auto: update
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
    replica:
      url: jdbc:mysql://localhost:33062/mydb?useSSL=false
      username: root
      password: root
      jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
            default_schema: read